apiVersion: v1
kind: Service
metadata:
  name: mvschool-dev-service
  labels:
    apptype: mvschool-dev
spec:
  type: ClusterIP
  selector:
    app: mvschool-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80